<a href="https://colab.research.google.com/github/vix2704/capgemini_training_assignments/blob/main/Machine-Learning/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KNN MODEL: CLASSIFICATION AND REGRESSION

In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer, fetch_california_housing
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error,precision_score,recall_score, f1_score,mean_absolute_error

In [99]:
cdata=load_breast_cancer()
cdata

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [100]:
df=pd.DataFrame(cdata.data,columns=cdata.feature_names)
df['cancer']=cdata.target
df

mean radius  mean texture  ...  worst fractal dimension  cancer
0          17.99         10.38  ...                  0.11890       0
1          20.57         17.77  ...                  0.08902       0
2          19.69         21.25  ...                  0.08758       0
3          11.42         20.38  ...                  0.17300       0
4          20.29         14.34  ...                  0.07678       0
..           ...           ...  ...                      ...     ...
564        21.56         22.39  ...                  0.07115       0
565        20.13         28.25  ...                  0.06637       0
566        16.60         28.08  ...                  0.07820       0
567        20.60         29.33  ...                  0.12400       0
568         7.76         24.54  ...                  0.07039       1

[569 rows x 31 columns]

In [101]:
X=df.drop('cancer',axis=1)
y=df['cancer']

In [102]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3, random_state=42)

In [103]:
model=KNeighborsClassifier(n_neighbors=10)
model.fit(Xtrain,ytrain)


KNeighborsClassifier(n_neighbors=10)

In [104]:
ypred=model.predict(Xtest)
ypred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [105]:
cmatrix=confusion_matrix(ytest,ypred)
cmatrix

array([[ 61,   2],
       [  1, 107]])

In [106]:
print('Training efficiency', model.score(Xtrain,ytrain))


Training efficiency 0.9271356783919598


In [107]:
print('Testing efficiency', model.score(Xtest,ytest))


Testing efficiency 0.9824561403508771


In [108]:
print('Accuracy', accuracy_score(ytest,ypred))


Accuracy 0.9824561403508771


In [109]:
print('Precision', precision_score(ytest,ypred))

Precision 0.981651376146789


In [110]:
print('Recall', recall_score(ytest,ypred))


Recall 0.9907407407407407


In [111]:
print('F1 score', f1_score(ytest,ypred))

F1 score 0.9861751152073732


In [112]:
# REGRESSOR

In [113]:
hdata=fetch_california_housing()
hdata

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [114]:
hf=pd.DataFrame(hdata.data,columns=hdata.feature_names)
hf['price']=hdata.target
hf

MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  price
0      8.3252      41.0  6.984127  ...     37.88    -122.23  4.526
1      8.3014      21.0  6.238137  ...     37.86    -122.22  3.585
2      7.2574      52.0  8.288136  ...     37.85    -122.24  3.521
3      5.6431      52.0  5.817352  ...     37.85    -122.25  3.413
4      3.8462      52.0  6.281853  ...     37.85    -122.25  3.422
...       ...       ...       ...  ...       ...        ...    ...
20635  1.5603      25.0  5.045455  ...     39.48    -121.09  0.781
20636  2.5568      18.0  6.114035  ...     39.49    -121.21  0.771
20637  1.7000      17.0  5.205543  ...     39.43    -121.22  0.923
20638  1.8672      18.0  5.329513  ...     39.43    -121.32  0.847
20639  2.3886      16.0  5.254717  ...     39.37    -121.24  0.894

[20640 rows x 9 columns]

In [115]:
X1=hf.drop('price',axis=1)
y1=hf['price']

In [116]:
X1train,X1test,y1train,y1test=train_test_split(X1,y1,test_size=0.3, random_state=10)

In [117]:
model1=KNeighborsRegressor(n_neighbors=2)
model1.fit(X1train,y1train)

KNeighborsRegressor(n_neighbors=2)

In [118]:
ypred1=model1.predict(X1test)
ypred1

array([1.3995, 2.303 , 1.1335, ..., 1.4445, 1.807 , 0.97  ])

In [119]:
print('Training efficiency', model1.score(X1train,y1train))

Training efficiency 0.6942146979269131


In [120]:
print('Testing efficiency', model1.score(X1test,y1test))

Testing efficiency 0.0512022024022446


In [121]:
print('MSE', mean_squared_error(y1test,ypred1))

MSE 1.2862295949284075


In [122]:
print('MAE',mean_absolute_error(y1test,ypred1))

MAE 0.8642631476098191
